In [1]:
import roboticstoolbox as rtb
import numpy as np
import spatialmath as sm
import spatialgeometry as sg

from math import *

#### 1.3.1) 
Calculate the rotation matrix corresponding to a $\theta=30^\circ$ rotation about the $x$ axis.

_Points:_ 2

In [2]:
# Express your answer as a 2D numpy array
R_131 = np.array([[1 , 0, 0],
                  [0 , cos(pi/6), -sin(pi/6)],
                  [0 , sin(pi/6), cos(pi/6)]])

#### 1.3.2) 
Calculate the rotation matrix corresponding to an extrinsic XYZ roll-pitch-yaw of $90^\circ$, $180^\circ$, and $270^\circ$, respectively.

_Points:_ 3

In [3]:
# Express your answer as a 2D numpy array
# Calculate the rotation matrix corresponding to an extrinsic XYZ roll-pitch-yaw of $90^\circ$, $180^\circ$, and $270^\circ$, respectively.

R_132 = sm.SO3.RPY([pi/2, pi, 3*pi/2], order='zyx')
R_132_2 = sm.SO3.Rz(3*pi/2) * sm.SO3.Ry(pi) * sm.SO3.Rx(pi/2)

R_132, R_132_2

(   0         0        -1         
   1         0         0         
   0        -1         0         
,
    0         0        -1         
   1         0         0         
   0        -1         0         
)

#### 1.3.3) 
Calculate the unit quaternion corresponding to the roll-pitch-yaw in the previous part. *Hint: you may find it useful to refer to the formula in the slides for converting between unit quaternions and rotation matrices.*

_Points:_ 3

In [4]:
R_132.R

array([[ 1.8369702e-16,  6.1232340e-17, -1.0000000e+00],
       [ 1.0000000e+00, -1.2246468e-16,  1.8369702e-16],
       [-1.2246468e-16, -1.0000000e+00, -6.1232340e-17]])

In [5]:
# Express your answer as a 1D numpy array
q_133 = R_132.UnitQuaternion()

#### 1.3.4) 
Calculate the axis-angle representation corresponding to the same roll-pitch-yaw in the previous part. *Hint: you may find it useful to refer to the formula in the slides for converting between unit quaternions and axis-angle representations.*

_Points:_ 3

In [6]:
aa_134 = q_133.angvec()
aa_134

(2.0943951023931953, array([-0.57735027, -0.57735027,  0.57735027]))

In [7]:
# Express your answer as two 2D numpy arrays
R_1351 = sm.SO3.RPY([pi/2, 0, 0], order='zyx')
R_1352 = sm.SO3.RPY([-pi/2, 0, 0], order='zyx')

R_1351 * R_1352, R_1352 * R_1351, R_1351, R_1352

(   1         0         0         
   0         1         0         
   0         0         1         
,
    1         0         0         
   0         1         0         
   0         0         1         
,
    1         0         0         
   0         0        -1         
   0         1         0         
,
    1         0         0         
   0         0         1         
   0        -1         0         
)

In [18]:
from spatialmath.base.symbolic import *  
import sympy

r, y = symbol('r y')
rot_mat = sm.SO3.RPY([r, -sympy.pi/2, y], order='zyx')
rot_mat

  0            -sin(r)*cos(y) - sin(y)*cos(r) sin(r)*sin(y) - cos(r)*cos(y)  
  0            -sin(r)*sin(y) + cos(r)*cos(y) -sin(r)*cos(y) - sin(y)*cos(r)  
  1            0            0             


### 2.1) 2D change of view-point

Some point $A$ is displaced from the origin of the world-coordinate frame $W$ by $3$ units in $W$'s $x$ direction and $4$ units in $W$'s $y$ direction. There is another coordinate frame $O$, which is displaced from $W$ by $2$ units in the negative $x$ direction of $W$ and $1$ unit in the $y$ direction of $W$, and rotated by $30^\circ$ counter-clockwise. Find the coordinates of point $A$ relative to frame $O$ expressed in frame $O$.

Your answer should be a $2\times 1$ numpy array.

_Points:_ 5

In [52]:
p = np.array([3, 4, 0])
o = sm.SE3([-2, 1, 0])
o.R = sm.SE3.Rz(sympy.pi/6)
T = sm.SE3()
T.t = p

In [53]:
p_OA = o.inv()*T.t
p_OA[:2]

array([[5.83012702],
       [0.09807621]])

### 2.2) 3D change of view-point

An object $O$ has an attached coordinate frame $O$, whose origin is at $(2,1,5)$ relative to the world frame $W$. Frame $O$ is rotated relative to $W$ by $90^\circ$ about the $z$ axis of $W$. There is a point $A$ in object $O$ at position $(1,0,0)$ relative to $O$. Find the world coordinates of point $A$. 

Your answer should be a $3\times 1$ numpy array.

_Points:_ 5

In [63]:
T_OW = sm.SE3([2, 1, 5])
T_OW.R = sm.SE3.Rz(sympy.pi/2)

p_AW = T_OW * sm.SE3([1, 0, 0])

p_AW.t

array([2., 2., 5.])