In [3]:
import roboticstoolbox as rtb
import numpy as np
import spatialmath as sm
import spatialgeometry as sg

from math import *

#### 1.2.1) 
Calculate the homogeneous transformation matrix representing a rotation of $\theta=45^\circ$ and a translation of 3 units in the $x$ direction. 

_Points:_ 2

In [20]:
# Express your answer as a 2D numpy array
X_121 = sm.SE2([3, 0, 45], unit='deg')

np.round(X_121.A, 3)

array([[ 0.707, -0.707,  3.   ],
       [ 0.707,  0.707,  0.   ],
       [ 0.   ,  0.   ,  1.   ]])

#### 1.2.2) 
Calculate the homogeneous transformation matrix representing a rotation of $\theta=120^\circ$ and a translation of 2 units in the $x$ direction and 1 unit in the $y$ direction.

_Points:_ 2

In [23]:
# Express your answer as a 2D numpy array
X_122 = sm.SE2([2, 1, 120], unit='deg')

np.round(X_122.A, 3)

array([[-0.5  , -0.866,  2.   ],
       [ 0.866, -0.5  ,  1.   ],
       [ 0.   ,  0.   ,  1.   ]])

#### 1.2.3) 
Calculate the homogeneous transformation matrix representing a rotation of $\theta=210^\circ$ and a translation of 4 units in the direction of $45^\circ$ above the $x$ axis. 

_Points:_ 2

In [48]:
# Express your answer as a 2D numpy array
wTa = sm.SE2([0, 0, 210], unit='deg')
wTb = sm.SE2([0, 0, 45], unit='deg') 
bTc = sm.SE2([4, 0, 0], unit='deg')

wTc = wTb * bTc
aTb = wTa.inv() * wTb
cTd = aTb

wTd = wTb * bTc * cTd

wTc.t

array([2.82842712, 2.82842712])

#### 1.3.1) 
Calculate the rotation matrix corresponding to a $\theta=30^\circ$ rotation about the $x$ axis.

_Points:_ 2

In [4]:
# Express your answer as a 2D numpy array
R_131 = np.array([[1 , 0, 0],
                  [0 , cos(pi/6), -sin(pi/6)],
                  [0 , sin(pi/6), cos(pi/6)]])

#### 1.3.2) 
Calculate the rotation matrix corresponding to an extrinsic XYZ roll-pitch-yaw of $90^\circ$, $180^\circ$, and $270^\circ$, respectively.

_Points:_ 3

In [5]:
# Express your answer as a 2D numpy array
# Calculate the rotation matrix corresponding to an extrinsic XYZ roll-pitch-yaw of $90^\circ$, $180^\circ$, and $270^\circ$, respectively.

R_132 = sm.SO3.RPY([pi/2, pi, 3*pi/2], order='zyx')
R_132_2 = sm.SO3.Rz(3*pi/2) * sm.SO3.Ry(pi) * sm.SO3.Rx(pi/2)

R_132, R_132_2

(   0         0        -1         
   1         0         0         
   0        -1         0         
,
    0         0        -1         
   1         0         0         
   0        -1         0         
)

#### 1.3.3) 
Calculate the unit quaternion corresponding to the roll-pitch-yaw in the previous part. *Hint: you may find it useful to refer to the formula in the slides for converting between unit quaternions and rotation matrices.*

_Points:_ 3

In [6]:
R_132.R

array([[ 1.8369702e-16,  6.1232340e-17, -1.0000000e+00],
       [ 1.0000000e+00, -1.2246468e-16,  1.8369702e-16],
       [-1.2246468e-16, -1.0000000e+00, -6.1232340e-17]])

In [7]:
# Express your answer as a 1D numpy array
q_133 = R_132.UnitQuaternion()

#### 1.3.4) 
Calculate the axis-angle representation corresponding to the same roll-pitch-yaw in the previous part. *Hint: you may find it useful to refer to the formula in the slides for converting between unit quaternions and axis-angle representations.*

_Points:_ 3

In [52]:
aa_134 = q_133.angvec()
aa_134[0] * aa_134[1]

array([-1.20919958, -1.20919958,  1.20919958])

In [9]:
# Express your answer as two 2D numpy arrays
R_1351 = sm.SO3.RPY([pi/2, 0, 0], order='zyx')
R_1352 = sm.SO3.RPY([-pi/2, 0, 0], order='zyx')

R_1351 * R_1352, R_1352 * R_1351, R_1351, R_1352

(   1         0         0         
   0         1         0         
   0         0         1         
,
    1         0         0         
   0         1         0         
   0         0         1         
,
    1         0         0         
   0         0        -1         
   0         1         0         
,
    1         0         0         
   0         0         1         
   0        -1         0         
)

In [17]:
from spatialmath.base.symbolic import *  
import sympy

r, y = symbol('r y')
rot_mat = sm.SO3.RPY([r, -sympy.pi/2, y], order='zyx')
rot_mat

rotz = sm.SO3.Rz(y)
roty = sm.SO3.Ry(-sympy.pi/2)
rotx = sm.SO3.Rx(r)

rotz * roty * rotx

  0            -sin(r)*cos(y) - sin(y)*cos(r) sin(r)*sin(y) - cos(r)*cos(y)  
  0            -sin(r)*sin(y) + cos(r)*cos(y) -sin(r)*cos(y) - sin(y)*cos(r)  
  1            0            0             


### 2.1) 2D change of view-point

Some point $A$ is displaced from the origin of the world-coordinate frame $W$ by $3$ units in $W$'s $x$ direction and $4$ units in $W$'s $y$ direction. There is another coordinate frame $O$, which is displaced from $W$ by $2$ units in the negative $x$ direction of $W$ and $1$ unit in the $y$ direction of $W$, and rotated by $30^\circ$ counter-clockwise. Find the coordinates of point $A$ relative to frame $O$ expressed in frame $O$.

Your answer should be a $2\times 1$ numpy array.

_Points:_ 5

In [37]:
p = np.array([3, 4, 0])
wTa = sm.SE2(p)
wTo = sm.SE2([-2, 1, 30], unit='deg')

oTa = wTo.inv() * wTa

oTa.t

array([5.83012702, 0.09807621])

In [ ]:
p_OA = o.inv()*T.t
p_OA[:2]

### 2.2) 3D change of view-point

An object $O$ has an attached coordinate frame $O$, whose origin is at $(2,1,5)$ relative to the world frame $W$. Frame $O$ is rotated relative to $W$ by $90^\circ$ about the $z$ axis of $W$. There is a point $A$ in object $O$ at position $(1,0,0)$ relative to $O$. Find the world coordinates of point $A$. 

Your answer should be a $3\times 1$ numpy array.

_Points:_ 5

In [ ]:
T_OW = sm.SE3([2, 1, 5])
T_OW.R = sm.SE3.Rz(sympy.pi/2)

p_AW = T_OW * sm.SE3([1, 0, 0])

p_AW.t

### 2.3) 2D action

A robot sarts at position (1,2) in the world frame, with its $x$-axis facing $45^\circ$ above the world's $x$ axis. The robot's gripper is at position $(0.1, 0.1)$ in the robot's frame. The robot moves forward 3 units along its $x$ axis and then rotates counter-clockwise by $90^\circ$. What is the final position of the robot's gripper in the world frame?

Your answer should be a $2\times 1$ numpy array.

_Points:_ 5

In [53]:
T_WR = sm.SE2([1, 2, 45], unit='deg')
T_RB = sm.SE2([3, 0, 90], unit='deg')
T_BE = sm.SE2([0.1, 0.1, 0])
T_EW = T_WR * T_RB * T_BE
T_EW.t.T


array([2.97989899, 4.12132034])

### 2.4) 3D action

Suppose we have a robot arm with a single spherical joint attached to a fixed table, connected to a link of length 2. The world coordinate frame is at the base of the link. Initially, the link is facing in the $x$ direction of the world frame and the gripper frame is rotated from the world frame by $-90^\circ$ about the $z$ axis, such that the $y$ frame points away from the gripper. The robot is grasping a box, whose center of mass is at position $(0, 0, 0.2)$ in the gripper frame. Calculate the position of the center of mass in the world frame after applying a rotation on the spherical joint given by:
$$R =\begin{pmatrix}
    0.306 & 0.787 & 0.536\\
    -0.521 & 0.61 & -0.598\\
    -0.797 & -0.096 & 0.597
\end{pmatrix}$$

Your answer should be a $3\times 1$ numpy array.

_Points:_ 5

In [ ]:

Rmat = np.array([[0.306, 0.787, 0.536], 
              [-0.521, 0.610, -0.598], 
              [-0.797, -0.096, 0.597]])
R_WJ = sm.SO3(Rmat, check=False)
T_WJ = sm.SE3(R_WJ)
T_JG = sm.SE3([2, 0, 0]) * sm.SE3.Rz(-90, unit='deg') # attention: first translated, then rotated
T_GB = sm.SE3([0, 0, 0.2])

T_WB = T_WJ * T_JG * T_GB

pos = T_WB.t

pos
